# Writes the list ResetEnvironment() calls: every Reset...Globals definition, then every
# Construct...Globals, each in link order (the order static constructors run in).
#
#   cmake -DSOURCE_LIST=<file of source paths, one a line> -DOUTPUT=<resets.inc> -P Resets.cmake

file(STRINGS "${SOURCE_LIST}" sources)
set(resets "")
set(constructs "")
foreach(source IN LISTS sources)
    file(STRINGS "${source}" lines REGEX "^(extern \"C\" )?void (Reset|Construct)[A-Za-z0-9_]*Globals\\(void\\)$")
    foreach(line IN LISTS lines)
        string(REGEX REPLACE "^.*void ([A-Za-z0-9_]+)\\(void\\)$" "\\1" name "${line}")
        if(name MATCHES "^Reset")
            string(APPEND resets "RESET_PHASE1(${name})\n")
        else()
            string(APPEND constructs "RESET_PHASE2(${name})\n")
        endif()
    endforeach()
endforeach()

set(text "/* Generated by cmake/Resets.cmake from the game sources; do not edit. */\n${resets}${constructs}")
# Only touch the file when the list changes, so reset.cpp rebuilds only then.
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" old)
endif()
if(NOT old STREQUAL text)
    file(WRITE "${OUTPUT}" "${text}")
endif()
