#include "u7/corpus.h"
#include "u7/generate.h"
#include "u7/lower.h"


#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char **argv) {
	bool detail = false;
	bool whole = false;
	bool generate = false;
	const char *write_path = NULL;
	int first = 1;
	while (first < argc && strncmp(argv[first], "--", 2) == 0) {
		if (strcmp(argv[first], "--detail") == 0) {
			detail = true;
		} else if (strcmp(argv[first], "--record") == 0) {
			whole = true;
		} else if (strcmp(argv[first], "--generate") == 0) {
			/* Jumps and layout rebuilt from structure, not from the original. */
			generate = true;
			whole = true;
		} else if (strncmp(argv[first], "--write=", 8) == 0) {
			write_path = argv[first] + 8;
			whole = true;
		}
		first += 1;
	}
	if (argc <= first) {
		fprintf(stderr, "usage: u7ucround [--detail] [--record] [--generate] <USECODE> ...\n");
		return 2;
	}

	int status = 0;
	for (int a = first; a < argc; ++a) {
		U7Corpus corpus;
		U7Result result = u7_corpus_load(argv[a], &corpus);
		if (result != U7_OK) {
			fprintf(stderr, "%s: %s\n", argv[a], u7_result_name(result));
			return 1;
		}

		size_t identical = 0;
		size_t wrong_size = 0;
		size_t wrong_bytes = 0;
		size_t refused = 0;
		size_t bytes_matched = 0;
		uint8_t *scratch = malloc(0x10000U);
		FILE *rebuilt = write_path != NULL ? fopen(write_path, "wb") : NULL;
		if (write_path != NULL && rebuilt == NULL) {
			fprintf(stderr, "%s: cannot write\n", write_path);
			free(scratch);
			u7_corpus_release(&corpus);
			return 1;
		}

		for (size_t i = 0; i < corpus.count && scratch != NULL; ++i) {
			const U7Function *function = &corpus.functions[i];

			U7Cfg cfg;
			U7Lifted lifted;
			memset(&lifted, 0, sizeof lifted);
			if (u7_cfg_build(function, &cfg) != U7_OK ||
					u7_lift_function(function, &cfg, u7_corpus_resolve, &corpus,
							&lifted) != U7_OK) {
				refused += 1U;
				u7_lifted_release(&lifted);
				u7_cfg_release(&cfg);
				continue;
			}

			U7LowerReport report;
			if (generate) {
				U7Structured structured;
				result = u7_structure_function(function, &cfg, &lifted, &structured);
				if (result == U7_OK) {
					result = u7_generate_function(function, &cfg, &lifted, &structured,
							scratch, 0x10000U, &report);
				}
				u7_structured_release(&structured);
			} else {
				result = whole
						? u7_lower_record(function, &cfg, &lifted, scratch, 0x10000U, &report)
						: u7_lower_function(function, &cfg, &lifted, scratch, 0x10000U,
								&report);
			}
			size_t expected = whole ? function->record_size : function->code_size;
			if (result != U7_OK) {
				refused += 1U;
				if (detail) {
					printf("    %04X refused at opcode %02X\n", function->function_id,
							report.failing_opcode);
				}
			} else if (report.identical) {
				identical += 1U;
				bytes_matched += report.code_size;
				if (rebuilt != NULL) {
					fwrite(scratch, 1U, report.code_size, rebuilt);
				}
			} else if (report.code_size != expected) {
				wrong_size += 1U;
				if (detail) {
					printf("    %04X produced %zu bytes, original has %zu\n",
							function->function_id, report.code_size, expected);
				}
				/* Anything not regenerated is written back unchanged, so the
				 * file still assembles and the difference stays visible. */
			} else {
				wrong_bytes += 1U;
				if (detail) {
					printf("    %04X differs first at +0x%zX\n", function->function_id,
							report.first_difference);
				}
			}

			if (rebuilt != NULL && !report.identical) {
				fwrite(function->data - 6U, 1U, function->record_size, rebuilt);
			}

			u7_lifted_release(&lifted);
			u7_cfg_release(&cfg);
		}
		if (rebuilt != NULL) {
			fclose(rebuilt);
			printf("  rebuilt file written to %s\n", write_path);
		}
		free(scratch);

		printf("%s\n", argv[a]);
		printf("  %zu functions\n", corpus.count);
		printf("  %s regenerated byte for byte: %zu (%zu bytes)\n",
				whole ? "whole records" : "code", identical, bytes_matched);
		printf("  wrong length: %zu, right length but different: %zu, refused: %zu\n",
				wrong_size, wrong_bytes, refused);
		if (identical != corpus.count) {
			status = 1;
		}
		u7_corpus_release(&corpus);
	}
	return status;
}
